// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  code: __t.string(),
  name: __t.string(),
  teamNumber: __t.u32(),
  role: __t.u32(),
  ruleset: __t.u32(),
  challenge: __t.u32(),
  crewSize: __t.u32(),
};
