// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.identity().primaryKey(),
  room: __t.string(),
  team: __t.u32(),
  role: __t.u32(),
  name: __t.string(),
  x: __t.f64(),
  z: __t.f64(),
  action: __t.bool(),
  seen: __t.u64(),
  online: __t.bool(),
});
