// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  host: __t.identity(),
  state: __t.string(),
  startAt: __t.u64().name("start_at"),
  created: __t.u64(),
  ruleset: __t.u32(),
  challenge: __t.u32(),
  crewSize: __t.u32().name("crew_size"),
});
